export const categories = [
  { id: 'all', label: '전체' },
  { id: 'game', label: '웹게임' },
  { id: 'flash', label: '짧은 게임' },
  { id: 'psych', label: '심리테스트' },
  { id: 'draw', label: '그리기' },
  { id: 'calc', label: '계산기' },
  { id: 'tool', label: '도구' },
  { id: 'ai', label: 'AI' },
  { id: 'made', label: '내가 만든 것' },
]

export const items = [
  {
    id: 'react-test',
    title: '반응속도 테스트',
    blurb: '초록불이 뜨면 누른다. 이 사이트 안에서 바로 끝나는 30초.',
    category: 'flash',
    kind: '내부',
    href: '/play/react',
    tags: ['내장', '집중'],
    stats: { day: 842, week: 5104, month: 16820, all: 40211 },
  },
  {
    id: 'doodle',
    title: '낙서장',
    blurb: '저장은 이 브라우저에만. 심심하면 선을 그어 둔다.',
    category: 'draw',
    kind: '내부',
    href: '/play/draw',
    tags: ['내장', '그림'],
    stats: { day: 611, week: 3902, month: 12044, all: 28810 },
  },
  {
    id: 'minute',
    title: '1분 숨고르기',
    blurb: '아무것도 안 하는 60초. 끝나면 다시 고른다.',
    category: 'tool',
    kind: '내부',
    href: '/play/minute',
    tags: ['내장', '타이머'],
    stats: { day: 390, week: 2104, month: 7440, all: 15102 },
  },
  {
    id: 'calc',
    title: '주머니 계산기',
    blurb: '팁, 더치, 퍼센트를 이 탭에서 끝낸다.',
    category: 'calc',
    kind: '내부',
    href: '/play/calc',
    tags: ['내장', '계산'],
    stats: { day: 274, week: 1688, month: 5901, all: 13340 },
  },
  {
    id: 'neal',
    title: 'Neal.fun',
    blurb: '인터넷의 쓸모없는 실험 모음. 하나 열면 옆 칸이 보인다.',
    category: 'game',
    kind: '외부',
    href: 'https://neal.fun',
    tags: ['실험', '영어'],
    stats: { day: 1204, week: 8044, month: 24110, all: 88021 },
  },
  {
    id: 'quickdraw',
    title: 'Quick, Draw!',
    blurb: '20초 안에 그리면 구글이 맞힌다.',
    category: 'draw',
    kind: '외부',
    href: 'https://quickdraw.withgoogle.com',
    tags: ['그림', 'AI'],
    stats: { day: 966, week: 6220, month: 19880, all: 64012 },
  },
  {
    id: '2048',
    title: '2048',
    blurb: '숫자 타일을 밀어 2048을 만든다. 한 판이 길다.',
    category: 'flash',
    kind: '외부',
    href: 'https://play2048.co',
    tags: ['퍼즐'],
    stats: { day: 1102, week: 7440, month: 22104, all: 91044 },
  },
  {
    id: 'little',
    title: 'Little Alchemy 2',
    blurb: '원소를 붙여 새 물건을 만든다. 수집형 킬링타임.',
    category: 'game',
    kind: '외부',
    href: 'https://littlealchemy2.com',
    tags: ['조합'],
    stats: { day: 733, week: 4510, month: 15002, all: 42018 },
  },
  {
    id: 'radio',
    title: 'Radio Garden',
    blurb: '지구본을 돌려 그 도시 라디오를 튼다.',
    category: 'tool',
    kind: '외부',
    href: 'https://radio.garden',
    tags: ['소리', '지도'],
    stats: { day: 588, week: 3660, month: 11990, all: 30551 },
  },
  {
    id: 'monkey',
    title: 'Monkeytype',
    blurb: '타자 속도. 1분만 해도 순위가 나온다.',
    category: 'tool',
    kind: '외부',
    href: 'https://monkeytype.com',
    tags: ['타자'],
    stats: { day: 804, week: 5122, month: 17004, all: 45590 },
  },
  {
    id: 'excal',
    title: 'Excalidraw',
    blurb: '손그림 느낌의 화이트보드. 설명 그림에 딱 맞다.',
    category: 'draw',
    kind: '외부',
    href: 'https://excalidraw.com',
    tags: ['그림', '협업'],
    stats: { day: 455, week: 2880, month: 9901, all: 24012 },
  },
  {
    id: 'photopea',
    title: 'Photopea',
    blurb: '브라우저 포토샵. 설치 없이 PSD를 연다.',
    category: 'tool',
    kind: '외부',
    href: 'https://www.photopea.com',
    tags: ['편집'],
    stats: { day: 512, week: 3401, month: 11220, all: 28990 },
  },
  {
    id: 'openpsych',
    title: 'OpenPsychometrics',
    blurb: '빅파이브와 고전 성격 검사를 길게 본다.',
    category: 'psych',
    kind: '외부',
    href: 'https://openpsychometrics.org',
    tags: ['심리', '영어'],
    stats: { day: 690, week: 4211, month: 13660, all: 35220 },
  },
  {
    id: 'human',
    title: 'Human Benchmark',
    blurb: '반응, 기억, 청력. 점수로 남는 미니 실험.',
    category: 'psych',
    kind: '외부',
    href: 'https://humanbenchmark.com',
    tags: ['테스트'],
    stats: { day: 477, week: 2994, month: 10110, all: 26604 },
  },
  {
    id: 'patatap',
    title: 'Patatap',
    blurb: '키보드를 누르면 소리와 도형이 같이 나온다.',
    category: 'game',
    kind: '외부',
    href: 'https://patatap.com',
    tags: ['소리'],
    stats: { day: 266, week: 1540, month: 4880, all: 14022 },
  },
  {
    id: 'useless',
    title: 'The Useless Web',
    blurb: '버튼을 누르면 쓸모없는 사이트로 던진다.',
    category: 'game',
    kind: '외부',
    href: 'https://theuselessweb.com',
    tags: ['랜덤'],
    stats: { day: 701, week: 4330, month: 12880, all: 39014 },
  },
  {
    id: 'window',
    title: 'Window Swap',
    blurb: '다른 사람 창밖을 10초만 본다.',
    category: 'tool',
    kind: '외부',
    href: 'https://www.window-swap.com',
    tags: ['풍경'],
    stats: { day: 318, week: 1902, month: 6400, all: 17110 },
  },
  {
    id: 'coolors',
    title: 'Coolors',
    blurb: '스페이스바로 색 조합을 돌린다.',
    category: 'tool',
    kind: '외부',
    href: 'https://coolors.co',
    tags: ['색'],
    stats: { day: 241, week: 1508, month: 4990, all: 13220 },
  },
  {
    id: 'desmos',
    title: 'Desmos',
    blurb: '그래프 계산기. 식을 치면 선이 움직인다.',
    category: 'calc',
    kind: '외부',
    href: 'https://www.desmos.com/calculator',
    tags: ['계산', '그래프'],
    stats: { day: 188, week: 1211, month: 4088, all: 11904 },
  },
  {
    id: 'agar',
    title: 'agar.io',
    blurb: '동그라미를 키우는 짧은 판. 한 판만.',
    category: 'flash',
    kind: '외부',
    href: 'https://agar.io',
    tags: ['멀티'],
    stats: { day: 955, week: 6402, month: 20110, all: 77040 },
  },
  {
    id: 'skribbl',
    title: 'skribbl.io',
    blurb: '그림 맞히기. 방 코드만 있으면 된다.',
    category: 'draw',
    kind: '외부',
    href: 'https://skribbl.io',
    tags: ['멀티', '그림'],
    stats: { day: 640, week: 4102, month: 13330, all: 36018 },
  },
  {
    id: 'cookie',
    title: 'Cookie Clicker',
    blurb: '쿠키를 누르는 게임. 켜 두고 잊기 좋다.',
    category: 'game',
    kind: '외부',
    href: 'https://orteil.dashnet.org/cookieclicker/',
    tags: ['클리커'],
    stats: { day: 512, week: 3550, month: 12140, all: 48022 },
  },
  {
    id: 'regex',
    title: 'Regex101',
    blurb: '정규식을 바로 시험한다. 개발 팁 게시판과 같이 보면 된다.',
    category: 'tool',
    kind: '외부',
    href: 'https://regex101.com',
    tags: ['개발'],
    stats: { day: 166, week: 990, month: 3440, all: 9804 },
  },
  {
    id: 'prompts-hall',
    title: '프롬프트 게시판',
    blurb: '써 본 AI 프롬프트를 짧게 붙여 둔다.',
    category: 'ai',
    kind: '내부',
    href: '/prompts',
    tags: ['AI', '공유'],
    stats: { day: 430, week: 2501, month: 8012, all: 16640 },
  },
]

export const seedPosts = [
  {
    id: 'p1',
    nick: '익명의 비둘기',
    tag: '홍보',
    title: '점심시간에 돌아가는 타자 놀이 올려 둠',
    body: '회사 와이파이에서도 열린다. 점수 저장은 없고, 한 판 30초다. 이상한 점 있으면 여기 달아 주세요.',
    created: '2026-09-28T03:12:00.000Z',
    comments: [
      { id: 'c1', nick: '익명의 고양이', body: '모바일에서 키 간격이 좁다.', created: '2026-09-28T05:01:00.000Z' },
    ],
  },
  {
    id: 'p2',
    nick: '익명의 너구리',
    tag: '리뷰',
    title: 'Radio Garden은 밤 이동 중에 잘 맞음',
    body: '도시 이름 모르고 찍는 재미가 있다. 광고는 거의 없고 로딩만 가끔 길다.',
    created: '2026-09-29T11:40:00.000Z',
    comments: [],
  },
  {
    id: 'p3',
    nick: '익명의 문어',
    tag: '질문',
    title: '심리테스트 직접 만든 사람 있음?',
    body: '결과 12개 정도로 짧게 만드는 구조가 궁금하다. 질문 수랑 결과 분기만 공유해 주면 된다.',
    created: '2026-09-30T08:20:00.000Z',
    comments: [
      { id: 'c2', nick: '익명의 여우', body: '질문 8개, 축 2개로 나누면 결과 4개로 끝난다. 12개는 축을 하나 더 두는 편.', created: '2026-09-30T09:02:00.000Z' },
    ],
  },
]

export const seedPrompts = [
  {
    id: 'pr1',
    title: '한 장짜리 심리테스트 결과 문장',
    model: '범용',
    body: '너는 심리테스트 작가다. 사용자 성향 키워드 3개를 받아, 판단하지 않는 말투로 결과 제목 1개와 본문 80자를 써라. 의학 진단처럼 쓰지 말 것.',
    nick: '익명의 여우',
  },
  {
    id: 'pr2',
    title: '웹게임 규칙 한 줄 다듬기',
    model: '범용',
    body: '아래 게임 규칙을 중학생도 읽는 한국어 한 줄로 줄여라. 조작, 목표, 끝나는 조건만 남겨라.',
    nick: '익명의 비둘기',
  },
  {
    id: 'pr3',
    title: '깃허브 README 첫 단락',
    model: '범용',
    body: '저장소 이름과 한 줄 설명을 받아 README 첫 단락을 써라. 기능 나열 대신 누가 언제 쓰는지부터 말하라. 과장 형용사 금지.',
    nick: '익명의 문어',
  },
]

export const seedTips = [
  {
    id: 't1',
    title: '바이브 코딩은 화면부터 고정한다',
    body: '기능 목록보다 첫 화면의 빈 상태를 먼저 그린다. 빈 상태가 있으면 데이터 없어도 배포할 수 있다.',
    github: 'https://github.com',
    nick: '익명의 너구리',
  },
  {
    id: 't2',
    title: '광고 자리는 높이부터 잡아 둔다',
    body: '애드센스 승인 전에 슬롯 높이를 비워 두면 나중에 레이아웃이 밀리지 않는다. ads.txt와 개인정보처리방침은 심사 전에 공개한다.',
    github: '',
    nick: '익명의 여우',
  },
  {
    id: 't3',
    title: '외부 링크는 새 탭, 클릭은 떠나기 전에 센다',
    body: 'window.open 전에 클릭 카운트를 올리면 이탈해도 지표가 남는다. 공유 지표는 브라우저 저장이 아니라 서버 카운터가 필요하다.',
    github: 'https://github.com',
    nick: '익명의 문어',
  },
]
