/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardRouteImport } from './routes/board'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as RankRouteImport } from './routes/rank'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as BoardIdRouteImport } from './routes/board.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as PlayCalcRouteImport } from './routes/play.calc'
import { Route as PlayDrawRouteImport } from './routes/play.draw'
import { Route as PlayMinuteRouteImport } from './routes/play.minute'
import { Route as PlayPickRouteImport } from './routes/play.pick'
import { Route as PlayPsychRouteImport } from './routes/play.psych'
import { Route as PlayReactRouteImport } from './routes/play.react'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoardRoute,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCalcRoute = PlayCalcRouteImport.update({
  id: '/play/calc',
  path: '/play/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDrawRoute = PlayDrawRouteImport.update({
  id: '/play/draw',
  path: '/play/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMinuteRoute = PlayMinuteRouteImport.update({
  id: '/play/minute',
  path: '/play/minute',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPickRoute = PlayPickRouteImport.update({
  id: '/play/pick',
  path: '/play/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPsychRoute = PlayPsychRouteImport.update({
  id: '/play/psych',
  path: '/play/psych',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReactRoute = PlayReactRouteImport.update({
  id: '/play/react',
  path: '/play/react',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/rank': typeof RankRoute
  '/share': typeof ShareRoute
  '/tips': typeof TipsRoute
  '/board/$id': typeof BoardIdRoute
  '/item/$id': typeof ItemIdRoute
  '/play/calc': typeof PlayCalcRoute
  '/play/draw': typeof PlayDrawRoute
  '/play/minute': typeof PlayMinuteRoute
  '/play/pick': typeof PlayPickRoute
  '/play/psych': typeof PlayPsychRoute
  '/play/react': typeof PlayReactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/rank': typeof RankRoute
  '/share': typeof ShareRoute
  '/tips': typeof TipsRoute
  '/board/$id': typeof BoardIdRoute
  '/item/$id': typeof ItemIdRoute
  '/play/calc': typeof PlayCalcRoute
  '/play/draw': typeof PlayDrawRoute
  '/play/minute': typeof PlayMinuteRoute
  '/play/pick': typeof PlayPickRoute
  '/play/psych': typeof PlayPsychRoute
  '/play/react': typeof PlayReactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/rank': typeof RankRoute
  '/share': typeof ShareRoute
  '/tips': typeof TipsRoute
  '/board/$id': typeof BoardIdRoute
  '/item/$id': typeof ItemIdRoute
  '/play/calc': typeof PlayCalcRoute
  '/play/draw': typeof PlayDrawRoute
  '/play/minute': typeof PlayMinuteRoute
  '/play/pick': typeof PlayPickRoute
  '/play/psych': typeof PlayPsychRoute
  '/play/react': typeof PlayReactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/privacy'
    | '/prompts'
    | '/rank'
    | '/share'
    | '/tips'
    | '/board/$id'
    | '/item/$id'
    | '/play/calc'
    | '/play/draw'
    | '/play/minute'
    | '/play/pick'
    | '/play/psych'
    | '/play/react'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/privacy'
    | '/prompts'
    | '/rank'
    | '/share'
    | '/tips'
    | '/board/$id'
    | '/item/$id'
    | '/play/calc'
    | '/play/draw'
    | '/play/minute'
    | '/play/pick'
    | '/play/psych'
    | '/play/react'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/privacy'
    | '/prompts'
    | '/rank'
    | '/share'
    | '/tips'
    | '/board/$id'
    | '/item/$id'
    | '/play/calc'
    | '/play/draw'
    | '/play/minute'
    | '/play/pick'
    | '/play/psych'
    | '/play/react'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PromptsRoute: typeof PromptsRoute
  RankRoute: typeof RankRoute
  ShareRoute: typeof ShareRoute
  TipsRoute: typeof TipsRoute
  ItemIdRoute: typeof ItemIdRoute
  PlayCalcRoute: typeof PlayCalcRoute
  PlayDrawRoute: typeof PlayDrawRoute
  PlayMinuteRoute: typeof PlayMinuteRoute
  PlayPickRoute: typeof PlayPickRoute
  PlayPsychRoute: typeof PlayPsychRoute
  PlayReactRoute: typeof PlayReactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/calc': {
      id: '/play/calc'
      path: '/play/calc'
      fullPath: '/play/calc'
      preLoaderRoute: typeof PlayCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/draw': {
      id: '/play/draw'
      path: '/play/draw'
      fullPath: '/play/draw'
      preLoaderRoute: typeof PlayDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/minute': {
      id: '/play/minute'
      path: '/play/minute'
      fullPath: '/play/minute'
      preLoaderRoute: typeof PlayMinuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/pick': {
      id: '/play/pick'
      path: '/play/pick'
      fullPath: '/play/pick'
      preLoaderRoute: typeof PlayPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/psych': {
      id: '/play/psych'
      path: '/play/psych'
      fullPath: '/play/psych'
      preLoaderRoute: typeof PlayPsychRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/react': {
      id: '/play/react'
      path: '/play/react'
      fullPath: '/play/react'
      preLoaderRoute: typeof PlayReactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardRouteChildren {
  BoardIdRoute: typeof BoardIdRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardIdRoute: BoardIdRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PromptsRoute: PromptsRoute,
  RankRoute: RankRoute,
  ShareRoute: ShareRoute,
  TipsRoute: TipsRoute,
  ItemIdRoute: ItemIdRoute,
  PlayCalcRoute: PlayCalcRoute,
  PlayDrawRoute: PlayDrawRoute,
  PlayMinuteRoute: PlayMinuteRoute,
  PlayPickRoute: PlayPickRoute,
  PlayPsychRoute: PlayPsychRoute,
  PlayReactRoute: PlayReactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
